# Generated by Django 6.0.3 on 2026-03-14 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("backend", "Backend Development"),
                            ("frontend", "Frontend Development"),
                            ("data_science", "Data Science"),
                            ("ml", "Machine Learning"),
                            ("ai_engineering", "AI Engineering"),
                            ("flutter", "Flutter Mobile"),
                            ("android", "Android Development"),
                            ("ios", "iOS Development"),
                            ("devops", "DevOps"),
                            ("cybersecurity", "Cybersecurity"),
                            ("blockchain", "Blockchain Development"),
                            ("game_dev", "Game Development"),
                            ("ui_ux", "UI/UX Design"),
                            ("cloud", "Cloud Engineering"),
                            ("qa", "QA / Testing"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("total_hours", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="RoadmapStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("hours_needed", models.PositiveIntegerField()),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="roadmap.roadmap",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="UserRoadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hours_per_day", models.PositiveIntegerField()),
                ("selected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roadmap.roadmap",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roadmaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "roadmap")},
            },
        ),
    ]
