# Generated by Django 6.0.3 on 2026-03-14 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        choices=[
                            ("backend", "Backend Development"),
                            ("frontend", "Frontend Development"),
                            ("data_science", "Data Science"),
                            ("ml", "Machine Learning"),
                            ("ai_engineering", "AI Engineering"),
                            ("flutter", "Flutter Mobile"),
                            ("android", "Android Development"),
                            ("ios", "iOS Development"),
                            ("devops", "DevOps"),
                            ("cybersecurity", "Cybersecurity"),
                            ("blockchain", "Blockchain Development"),
                            ("game_dev", "Game Development"),
                            ("ui_ux", "UI/UX Design"),
                            ("cloud", "Cloud Engineering"),
                            ("qa", "QA / Testing"),
                        ],
                        max_length=50,
                    ),
                ),
                ("percentage", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-percentage"],
            },
        ),
    ]
